---

- name: install access
  hosts: access
  gather_facts: False
  vars:
    root_dir: ../..
    tomcat_dir: /usr/local/apache-tomcat-9.0.0.M17
    access_dir: "{{ tomcat_dir }}/www/fsp-access"
  vars_files:
    - "{{ root_dir }}/vars/global_vars.yml"
  tasks:
    - name: create fsp-access directory
      file:
        path: "{{ access_dir }}"
        state: directory

    - name: extract access
      unarchive:
        src: "{{ root_dir }}/files/java/fsp-access.war"
        dest: "{{ access_dir }}"

    - name: copy access config
      template:
        src: "{{ root_dir }}/templates/access.init.properties.j2"
        dest: "{{ access_dir }}/WEB-INF/classes/init.properties"

    - name: read access config
      command: "cat {{ root_dir }}/files/access/access.xml"
      register: access_xml
      delegate_to: localhost

    - name: insert to server.xml
      blockinfile:
        path: "{{ tomcat_dir }}/conf/server.xml"
        marker: "<!-- {mark} Access Service -->"
        insertafter: "</Service>"
        content: "{{ access_xml.stdout }}"
