---

- name: install icegrid-registry
  hosts: icegrid-registry
  gather_facts: False
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/global_vars.yml"
  tasks:
    - name: make master directory
      file:
        path: /opt/ice/master/db/master
        state: directory

    - name: copy master config
      copy:
        src: "{{ root_dir }}/files/cpp/icegrid/master/config.master"
        dest: /opt/ice/master

    - name: make application directory
      file:
        path: /opt/ice/application
        state: directory

    # TODO: test_ice_server problem!
    - name: copy application config
      copy:
        src: "{{ root_dir }}/files/ice/application.xml"
        dest: /opt/ice/application
    
    - name: copy registry client config
      template:
        src: "{{ root_dir }}/templates/config.client.j2"
        dest: /opt/ice/application/config.client
