---

- name: install redis
  hosts: redis
  gather_facts: False
  vars:
    root_dir: ../..
  tasks:
    - name: uncompress redis
      unarchive:
        src: "{{ root_dir }}/files/redis/redis-3.2.6.tar.gz"
        dest: "/usr/local/"

    - name: copy redis config
      copy:
        src: "{{ root_dir }}/files/redis/redis.conf"
        dest: /usr/local/redis-3.2.6

    - name: copy sentinel config
      copy:
        src: "{{ root_dir }}/files/redis/sentinel.conf"
        dest: /usr/local/redis-3.2.6

    - name: set REDIS_HOME
      lineinfile: 
        path: /etc/profile
        line: 'REDIS_HOME=/usr/local/redis-3.2.6'

    - name: set PATH
      lineinfile:
        path: /etc/profile
        line: 'export PATH=$PATH:$REDIS_HOME'
       
