---

- name: install base
  hosts: all
  gather_facts: False

  vars:
    root_dir: ../..

  tasks:
    - name: install wget
      yum:
        name: wget
        state: installed
    
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: installed

    - name: install unzip
      yum:
        name: unzip
        state: installed
