---

- name: install base
  hosts: all
  gather_facts: True

  vars:
    root_dir: ../..

  tasks:
    - name: rebuild rpmdb
      shell: "rpm --rebuilddb"

    - name: install wget
      yum:
        name: wget
        state: installed

    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: installed

    - name: install unzip
      yum:
        name: unzip
        state: installed
