---

- name: install baselib
  hosts: all
  gather_facts: False

  vars:
    root_dir: ../..

  tasks:
    - name: copy base lib
      copy:
        src: "{{ root_dir }}/files/base/"
        dest: /usr/local/lib
        mode: 0755

    - name: create libstdc++ link
      file:
        src: /usr/local/lib/libstdc++.so.6.0.20
        dest: /usr/local/lib/libstdc++.so.6
        state: link

    - name: create libjsoncpp link
      file:
        src: /usr/local/lib/libjsoncpp.so.1
        dest: /usr/local/lib/libjsoncpp.so.0
        state: link
    
    - name: create libjsoncpp link
      file:
        src: /usr/local/lib/libjsoncpp.so.0
        dest: /usr/local/lib/libjsoncpp.so
        state: link
    
    - name: create pb link
      file:
        src: /usr/local/lib/libprotobuf.so.12.0.0
        dest: /usr/local/lib/libprotobuf.so.12
        state: link
    
    - name: create pb link
      file:
        src: /usr/local/lib/libprotobuf.so.12
        dest: /usr/local/lib/libprotobuf.so
        state: link

    - name: add path into ld.so.conf
      lineinfile:
        path: /etc/ld.so.conf
        line: "/usr/local/lib"
        state: present

    - name: ldconfig
      shell: "ldconfig"
