---

- name: install as
  hosts: as
  remote_user: root
  gather_facts: True
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/global_vars.yml"
  tasks:
    - name: extract FMServer
      unarchive:
        src: "{{ root_dir }}/files/as/FM_Server5.1.0.1.tar.gz"
        dest: /opt/

    - name: install FMMonitor
      shell: "./install.sh monitor"
      args:
        chdir: /opt/FMServerInstall/

    - name: install FMServer-main
      shell: "./install.sh main"
      args:
        chdir: /opt/FMServerInstall/

    - name: install FMServer-node
      shell: "./install.sh node"
      args:
        chdir: /opt/FMServerInstall/

    - name: copy ServiceConfig.xml
      template:
        src: "{{ root_dir }}/templates/ServiceConfig.xml.j2"
        dest: "/fsmeeting/FM_Server/bin/FMServer/ServiceConfig.xml"

    - name: copy AccessConfig.xml
      template:
        src: "{{ root_dir }}/templates/AccessConfig.xml.j2"
        dest: "/fsmeeting/FM_Server/bin/FMServer/AccessConfig.xml"
      
    - name: copy ice.property.cfg
      template:
        src: "{{ root_dir }}/templates/ice.property.cfg.j2"
        dest: "/fsmeeting/FM_Server/bin/FMServer/ice.property.cfg"
    
    - name: copy CascadeConfig.xml
      copy:
        src: "{{ root_dir }}/files/as/CascadeConfig.xml"
        dest: "/fsmeeting/FM_Server/bin/FMServer/"

    - name: copy iplib.db
      copy:
        src: "{{ root_dir }}/files/as/iplib.db"
        dest: "/fsmeeting/FM_Server/bin/FMServer/"
    
