---

- name: shutdown FMMonitor and FMServer
  hosts: as
  gather_facts: False
  tasks:
    - name: shutdown FMMonitor
      service:
        name: FMMonitor
        state: stopped
      ignore_errors: yes

    - name: shutdown FMServer
      service:
        name: FMServer
        state: stopped
      ignore_errors: yes

    - name: check process
      shell: "ps ax | grep FM"
      register: result

    - name: check FMServer
      fail: msg="shutdown FMServer failed"
      when: result.stdout.find('FM_Server') != -1

    - name: check FMMonitor
      fail: msg="shutdown FMMonitor failed"
      when: result.stdout.find('FMMonitor') != -1
