---

- name: shutdown kafka
  hosts: kafka
  gather_facts: False
  tasks:
    - name: execute shutdown command
      shell: "./kafka-server-stop.sh"
      args:
        chdir: /usr/local/kafka_2.11-0.10.1.1/bin
      ignore_errors: yes

    - name: show kafka shutdown result
      shell: "jps"
      register: result
      failed_when: result.stdout.find('Kafka') != -1
