---

- name: shutdown kafka
  hosts: kafka
  gather_facts: False
  tasks:
    - name: execute shutdown command
      shell: "./kafka-server-stop.sh"
      args:
        chdir: /usr/local/kafka_2.11-0.10.1.1/bin
      ignore_errors: yes

    - name: show kafka shutdown result
      shell: "jps"
      register: check_result

    - block:
      
      - name: kill kafka process
        shell: "ps ax | grep -i 'kafka.Kafka' | grep java | grep -v grep | awk '{print $1}' | xargs kill -9"
        
      - name: check if kafka process exists
        shell: "jps"
        register: result

      - name: kill process success
        debug: msg="stop kafka success"
        when: result.stdout.find('Kafka') == -1      
     
      - name: kill process failed
        debug: msg="stop kafka failed"
        when: result.stdout.find('Kafka') != -1      

      when: check_result.stdout.find('Kafka') != -1
