---

- name: install kafka
  hosts: kafka
  remote_user: root
  gather_facts: True
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/global_vars.yml" 
  tasks:
    - name: uncompress kafka
      unarchive:
        src: "{{ root_dir }}/files/kafka/kafka_2.11-0.10.1.1.tgz"
        dest: "/usr/local/"

    - name: copy kafka config
      template:
        src: "{{ root_dir }}/templates/kafka.server.properties.j2"
        dest: /usr/local/kafka_2.11-0.10.1.1/config/server.properties 
