---

- name: install ice
  hosts: ice
  gather_facts: False

  tasks:
    - name: uncompress ice
      unarchive:
        src: "files/Ice-3.5.1.tar.gz"
        dest: "/usr/local/"

    - name: set ICE_HOME
      lineinfile:
        path: /etc/profile
        line: 'ICE_HOME=/usr/local/Ice-3.5.1'

    - name: set PATH
      lineinfile:
        path: /etc/profile
        line: 'export PATH=$PATH:$ICE_HOME'
    
    - name: set LD_LIBRARY_PATH
      lineinfile:
        path: /etc/profile
        line: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ICE_HOME/lib:$ICE_HOME/lib64'

    - name: source
      shell: "source /etc/profile"

