---

- name: install icegrid-node
  hosts: icegrid-node1
  gather_facts: False
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/servers.yml"
  tasks:
    - name: create dir
      file:
        path: /opt/ice/node1/db/node1
        state: directory
    
    - name: copy node config
      template:
        src: "{{ root_dir }}/templates/config.server.j2"
        dest: /opt/ice/node1/config.server

    - name: copy server binary
      copy:
        src: "{{ root_dir }}/files/ice/icegrid/node1/ice_server"
        dest: /opt/ice/node1

    - name: set file mode
      file:
        path: /opt/ice/node1/ice_server
        mode: 0744
