---

- name: install gc
  hosts: gc
  gather_facts: False
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/global_vars.yml"
  tasks:
    - name: extract gc package
      unarchive:
        src: "{{ root_dir }}/files/java/fsp-gc-1.0-SNAPSHOT-assembly.tar.gz"
        dest: "/opt/"

    - name: copy gc config
      template:
        src: "{{ root_dir }}/templates/gc.init.properties.j2"
        dest: "/opt/fsp-gc-1.0-SNAPSHOT/conf/init.properties"
