---

- name: install ma
  hosts: ma
  gather_facts: False
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/servers.yml"
  tasks:
    - name: extract ma
      unarchive:
        src: "{{ root_dir }}/files/java/fsp-ma-1.0-SNAPSHOT-assembly.tar.gz"
        dest: "/opt/"

    - name: copy ma config
      template:
        src: "{{ root_dir }}/templates/ma.init.properties.j2"
        dest: "/opt/fsp-ma-1.0-SNAPSHOT/conf/init.properties"
