---

- name: install ms
  hosts: ms
  gather_facts: False
  vars:
    root_dir: ../..
  vars_files:
    - "{{ root_dir }}/vars/servers.yml"
  tasks:
    - name: uncompress ms
      unarchive:
        src: "{{ root_dir }}/files/java/fsp-ms-1.0-SNAPSHOT-assembly.tar.gz"
        dest: "/opt/"

    - name: copy ms config
      template:
        src: "{{ root_dir }}/templates/ms.init.properties.j2"
        dest: "/opt/fsp-ms-1.0-SNAPSHOT/conf/init.properties"
