---

- name: start tomcat
  hosts: tomcat
  gather_facts: False
  tags:
    - run_tomcat
  tasks:
    - name: check if tomcat is already running
      shell: "ps x | grep tomcat"
      register: check_result

    - name: tomcat is already running
      debug: msg="tomcat is already running"
      when: check_result.stdout.find(' start') != -1

    - block:
      - name: startup tomcat
        shell: "./startup.sh"
        args:
          chdir: /usr/local/apache-tomcat-9.0.0.M17/bin
        register: result

      - name: check if tomcat is running
        shell: "ps x | grep tomcat"
        register: result

      - name: start tomcat success
        debug: msg="start tomcat success"
        when: result.stdout.find(' start') != -1

      - name: start tomcat failed
        fail: msg="start tomcat failed"
        when: result.stdout.find(' start') == -1
      when: check_result.stdout.find(' start') == -1
