---

- name: start SC
  hosts: sc
  gather_facts: False
  tags:
    - run_sc
  tasks:
    # sc_start.sh can check if MA is running by itself
    - name: execute run command
      shell: "./sc_start.sh"
      args:
        chdir: /opt/fsp-sc/bin
      ignore_errors: yes

    - name: jps
      shell: "jps"
      register: result

    - name: show SC run result
      debug:
        msg: "Start SC success"
      when: result.stdout.find('SC') != -1
