---

- name: run rule
  hosts: rule
  gather_facts: False
  tags:
    - run_rule
  tasks:
    # rule_start.sh can check if MA is running by itself
    - name: execute run command
      shell: "./rule_start.sh"
      args:
        chdir: /opt/fsp-rule-1.0-SNAPSHOT/bin
      ignore_errors: yes

    - name: jps
      shell: "jps"
      register: result

    - name: show rule run result
      debug:
        msg: "Start rule success"
      when: result.stdout.find('Rule') != -1
