---

- name: run zk
  hosts: zk
  remote_user: root
  tags:
    - run_zk
  tasks:
    - name: check if zk is running
      shell: "ps ax | grep zoo"
      register: check_result

    - name: zookeeper is running
      debug: msg="zookeeper is already running"
      when: check_result.stdout.find('zoo.cfg') != -1

    - block:
      - name: execute run command
        shell: "./zkServer.sh start"
        args:
          chdir: /usr/local/zookeeper-3.4.9/bin
        register: result

      - name: show run result
        debug:
          msg: "Start zookeeper success"
        when: (result.stdout.find('already running') != -1) or
              (result.stdout.find('Started') != -1)
      when: check_result.stdout.find('zoo.cfg') == -1
