---

- name: start FMMonitor and FMServer
  hosts: fmserver
  gather_facts: False
  tags:
    - run_as
  tasks:
    - name: start FMServer
      service:
        name: FMServer
        state: started

    - name: start FMMonitor
      service:
        name: FMMonitor
        state: started
